apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: go-hrms
  name: go-hrms
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: go-hrms
  template:
    metadata:
      labels:
        app.kubernetes.io/name: go-hrms
    spec:
      containers:
      - image: go-hrms:latest
        name: go-hrms
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: MY-PORT
          value: "3000"